<?php

return [
    'pages' => ['global', 'home', 'about', 'services', 'products', 'careers', 'blogs', 'contact', 'faq'],

    'labels' => [
        'global' => [
            'site_logo_desktop' => 'Header logo (desktop)',
            'site_logo_mobile' => 'Header logo (mobile)',
            'site_logo_footer' => 'Footer logo',
            'footer_tagline' => 'Footer — tagline text',
            'social_instagram' => 'Social — Instagram URL',
            'social_linkedin' => 'Social — LinkedIn URL',
            'social_facebook' => 'Social — Facebook URL',
        ],
        'home' => [
            'hero' => 'Hero — headline & description',
            'hero_badge' => 'Hero — trust badge text',
            'hero_bg' => 'Hero — background image',
            'hero_image' => 'Hero — side image',
            'stat_1' => 'Stats bar — item 1',
            'stat_2' => 'Stats bar — item 2',
            'stat_3' => 'Stats bar — item 3',
            'services_header' => 'Services section — heading',
            'why_header' => 'Why partner — heading',
            'why_partner_1' => 'Why partner — card 1',
            'why_partner_2' => 'Why partner — card 2',
            'why_partner_3' => 'Why partner — card 3',
            'process_header' => 'Process section — heading',
            'process_step_1' => 'Process — step 1',
            'process_step_2' => 'Process — step 2',
            'process_step_3' => 'Process — step 3',
            'process_step_4' => 'Process — step 4',
            'impact_header' => 'Impact section — heading',
            'impact_1' => 'Impact — stat 1',
            'impact_2' => 'Impact — stat 2',
            'impact_3' => 'Impact — stat 3',
            'impact_4' => 'Impact — stat 4',
            'testimonials_header' => 'Testimonials — heading',
            'testimonial_1' => 'Testimonial 1',
            'testimonial_2' => 'Testimonial 2',
            'testimonial_3' => 'Testimonial 3',
            'gallery_header' => 'Gallery section — heading',
            'gallery_1' => 'Gallery — image 1',
            'gallery_2' => 'Gallery — image 2',
            'gallery_3' => 'Gallery — image 3',
            'gallery_4' => 'Gallery — image 4',
            'gallery_5' => 'Gallery — image 5',
            'gallery_6' => 'Gallery — image 6',
            'gallery_7' => 'Gallery — image 7',
            'gallery_8' => 'Gallery — image 8',
            'faq_header' => 'FAQ section — heading',
            'cta' => 'Bottom CTA — text',
        ],
        'about' => [
            'hero' => 'About page — hero',
            'overview' => 'Company overview',
            'who_we_are' => 'Who we are paragraph',
            'milestone_1' => 'Timeline — milestone 1',
            'milestone_2' => 'Timeline — milestone 2',
            'milestone_3' => 'Timeline — milestone 3',
            'milestone_4' => 'Timeline — milestone 4',
            'location_1' => 'Location 1',
            'location_2' => 'Location 2',
            'location_3' => 'Location 3',
            'why_choose' => 'Why choose us — heading',
            'why_choose_1' => 'Why choose — card 1',
            'why_choose_2' => 'Why choose — card 2',
            'why_choose_3' => 'Why choose — card 3',
            'cta' => 'Bottom CTA',
        ],
        'services' => ['hero' => 'Services page — hero'],
        'products' => ['hero' => 'Products page — hero'],
        'careers' => ['hero' => 'Careers page — hero'],
        'blogs' => ['hero' => 'Blogs page — hero'],
        'contact' => ['hero' => 'Contact page — hero'],
        'faq' => ['hero' => 'FAQ page — hero'],
    ],

    'hints' => [
        'hero_bg' => 'Full-width background behind the hero section.',
        'hero_image' => 'Main hero image shown on the right side.',
        'stat_1' => 'Use Title for the number (e.g. 1000+), Subtitle for the label.',
        'stat_2' => 'Use Title for the number, Subtitle for the label.',
        'stat_3' => 'Use Title for the number, Subtitle for the label.',
        'why_partner_1' => 'Icon field: emoji or Font Awesome class (e.g. fa-bolt).',
        'process_step_1' => 'Title = step name, Content = description.',
        'impact_1' => 'Title = number/stat, Subtitle or Content = label.',
        'testimonial_1' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_2' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_3' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'gallery_1' => 'Upload gallery image (recommended 560×400px).',
        'site_logo_desktop' => 'Shown in the header on desktop screens.',
        'site_logo_mobile' => 'Shown in the header on mobile screens.',
        'site_logo_footer' => 'Shown in the website footer.',
        'footer_tagline' => 'Short description shown below the footer logo.',
        'social_instagram' => 'Use the Link field for the full Instagram URL.',
        'social_linkedin' => 'Use the Link field for the full LinkedIn URL.',
        'milestone_1' => 'Subtitle = year, Title = milestone name, Content = description.',
        'location_1' => 'Title = city name, Subtitle = office type (e.g. Head Office).',
    ],
];
