<?php

return [
    'pages' => ['global', 'home', 'services', 'products', 'careers', 'blogs', 'contact'],

    'labels' => [
        'global' => [
            'site_logo_desktop' => 'Header logo (desktop)',
            'site_logo_mobile' => 'Header logo (mobile)',
            'site_logo_footer' => 'Footer logo',
        ],
        'home' => [
            'hero' => 'Hero — headline & description',
            'hero_badge' => 'Hero — top badge',
            'hero_bg' => 'Hero — background image',
            'hero_image' => 'Hero — side phone image',
            'feature_1' => 'Hero — quick feature 1',
            'feature_2' => 'Hero — quick feature 2',
            'feature_3' => 'Hero — quick feature 3',
            'feature_4' => 'Hero — quick feature 4',
            'stat_1' => 'Stats bar — item 1',
            'stat_2' => 'Stats bar — item 2',
            'stat_3' => 'Stats bar — item 3',
            'stat_4' => 'Stats bar — item 4',
            'features_header' => 'Features section — heading',
            'platform_feature_1' => 'Features grid — card 1',
            'platform_feature_2' => 'Features grid — card 2',
            'platform_feature_3' => 'Features grid — card 3',
            'platform_feature_4' => 'Features grid — card 4',
            'platform_feature_5' => 'Features grid — card 5',
            'platform_feature_6' => 'Features grid — card 6',
            'mobile_app' => 'Mobile app — text block',
            'mobile_phone_left' => 'Mobile app — left phone image',
            'mobile_phone_right' => 'Mobile app — right phone image',
            'play_store' => 'Mobile app — Play Store badge & link',
            'about' => 'About section',
            'promise_card' => 'About — promise card',
            'testimonials_header' => 'Testimonials — heading',
            'testimonial_1' => 'Testimonial 1',
            'testimonial_2' => 'Testimonial 2',
            'testimonial_3' => 'Testimonial 3',
            'cta' => 'Bottom CTA — text',
            'cta_bg' => 'Bottom CTA — background image',
        ],
        'services' => ['hero' => 'Services page — hero'],
        'products' => ['hero' => 'Products page — hero'],
        'careers' => ['hero' => 'Careers page — hero'],
        'blogs' => ['hero' => 'Blogs page — hero'],
        'contact' => ['hero' => 'Contact page — hero'],
    ],

    'hints' => [
        'hero_bg' => 'Full-width background behind the hero section.',
        'hero_image' => 'Phone mockup shown on the right side of the hero.',
        'stat_1' => 'Use Title for the number (e.g. 1000+), Subtitle for the label, Icon for Font Awesome class.',
        'stat_2' => 'Use Title for the number, Subtitle for the label, Icon for Font Awesome class.',
        'stat_3' => 'Use Title for the number, Subtitle for the label, Icon for Font Awesome class.',
        'stat_4' => 'Use Title for the number, Subtitle for the label, Icon for Font Awesome class.',
        'platform_feature_1' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'platform_feature_2' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'platform_feature_3' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'platform_feature_4' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'platform_feature_5' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'platform_feature_6' => 'Upload an icon image (recommended 75×75px). Title = card heading, Content = description.',
        'play_store' => 'Upload Play Store badge image. Use Link field for the Play Store URL.',
        'testimonial_1' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_2' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_3' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'cta_bg' => 'Background image for the bottom call-to-action banner.',
        'site_logo_desktop' => 'Shown in the header on desktop screens.',
        'site_logo_mobile' => 'Shown in the header on mobile screens.',
        'site_logo_footer' => 'Shown in the website footer.',
    ],
];
