<?php

return [
    'pages' => ['global', 'home', 'about', 'services', 'products', 'careers', 'blogs', 'contact', 'faq'],

    'labels' => [
        'global' => [
            'site_logo_desktop' => 'Header logo (desktop)',
            'site_logo_mobile' => 'Header logo (mobile)',
            'site_logo_footer' => 'Footer logo',
            'footer_tagline' => 'Footer — tagline text',
            'social_instagram' => 'Social — Instagram URL',
            'social_linkedin' => 'Social — LinkedIn URL',
            'social_facebook' => 'Social — Facebook URL',
            'nav_home' => 'Nav — Home label',
            'nav_about' => 'Nav — About label',
            'nav_services' => 'Nav — Services label',
            'nav_services_all' => 'Nav — All Services label',
            'nav_products' => 'Nav — Products label',
            'nav_blogs' => 'Nav — Blog label',
            'nav_careers' => 'Nav — Careers label',
            'nav_faq' => 'Nav — FAQ label',
            'nav_contact' => 'Nav — Contact label',
            'nav_login' => 'Nav — Employee Login label',
            'nav_cta' => 'Header CTA button (Title)',
            'footer_col_services' => 'Footer column — Services heading',
            'footer_col_company' => 'Footer column — Company heading',
            'footer_col_support' => 'Footer column — Support heading',
            'footer_link_about' => 'Footer — About Us label',
            'footer_link_contact' => 'Footer — Contact Us label',
            'footer_copyright' => 'Footer — copyright suffix (after year/company)',
            'footer_privacy' => 'Footer — Privacy Policy label',
            'footer_terms' => 'Footer — Terms of Service label',
        ],
        'home' => [
            'hero' => 'Hero — headline & description',
            'hero_badge' => 'Hero — trust badge text',
            'hero_bg' => 'Hero — background image',
            'hero_image' => 'Hero — side image (legacy single)',
            'hero_slide_1' => 'Hero carousel — image 1',
            'hero_slide_2' => 'Hero carousel — image 2',
            'hero_slide_3' => 'Hero carousel — image 3',
            'hero_slide_4' => 'Hero carousel — image 4',
            'stat_1' => 'Hero mini-stat — item 1',
            'stat_2' => 'Hero mini-stat — item 2',
            'stat_3' => 'Hero mini-stat — item 3',
            'services_header' => 'Services section — heading',
            'why_header' => 'Why partner — heading',
            'why_partner_1' => 'Why partner — card 1',
            'why_partner_2' => 'Why partner — card 2',
            'why_partner_3' => 'Why partner — card 3',
            'process_header' => 'Process section — heading',
            'process_image_1' => 'Process — left carousel image 1',
            'process_image_2' => 'Process — left carousel image 2',
            'process_image_3' => 'Process — left carousel image 3',
            'process_step_1' => 'Process — step/card 1',
            'process_step_2' => 'Process — step/card 2',
            'process_step_3' => 'Process — step/card 3',
            'process_step_4' => 'Process — step/card 4',
            'impact_header' => 'Impact section — heading',
            'impact_1' => 'Impact — stat 1',
            'impact_2' => 'Impact — stat 2',
            'impact_3' => 'Impact — stat 3',
            'impact_4' => 'Impact — stat 4',
            'testimonials_header' => 'Testimonials — heading',
            'testimonial_1' => 'Testimonial 1',
            'testimonial_2' => 'Testimonial 2',
            'testimonial_3' => 'Testimonial 3',
            'gallery_header' => 'Gallery section — heading',
            'gallery_1' => 'Gallery — image 1',
            'gallery_2' => 'Gallery — image 2',
            'gallery_3' => 'Gallery — image 3',
            'gallery_4' => 'Gallery — image 4',
            'gallery_5' => 'Gallery — image 5',
            'gallery_6' => 'Gallery — image 6',
            'gallery_7' => 'Gallery — image 7',
            'gallery_8' => 'Gallery — image 8',
            'faq_header' => 'FAQ section — heading',
            'cta' => 'Bottom CTA — text',
        ],
        'about' => [
            'hero' => 'Hero — eyebrow, headline & lead',
            'hero_bg' => 'Hero — background image',
            'hero_meta_1' => 'Hero meta — item 1 (e.g. Origin)',
            'hero_meta_2' => 'Hero meta — item 2 (e.g. Route)',
            'hero_meta_3' => 'Hero meta — item 3 (e.g. Verticals)',
            'hero_meta_4' => 'Hero meta — item 4 (e.g. Status)',
            'story_header' => 'Story — section heading',
            'story' => 'Story — body text (paragraphs)',
            'story_image' => 'Story — photo (+ Title = photo tag)',
            'about_stat_1' => 'Story stats — item 1',
            'about_stat_2' => 'Story stats — item 2',
            'about_stat_3' => 'Story stats — item 3',
            'about_stat_4' => 'Story stats — item 4',
            'vision_header' => 'Vision — section heading',
            'vision_quote' => 'Vision — quote',
            'vision_point_1' => 'Vision — point 1',
            'vision_point_2' => 'Vision — point 2',
            'vision_image' => 'Vision — photo',
            'why_header' => 'Why us — section heading',
            'issue_1' => 'Issue card 1 (Title=issue, Content=problem, Subtitle=solution)',
            'issue_2' => 'Issue card 2',
            'issue_3' => 'Issue card 3',
            'issue_4' => 'Issue card 4',
            'advantage_header' => 'Advantage strip — label',
            'advantage_1' => 'Advantage card 1',
            'advantage_2' => 'Advantage card 2',
            'advantage_3' => 'Advantage card 3',
            'advantage_4' => 'Advantage card 4',
            'advantage_5' => 'Advantage card 5',
            'advantage_6' => 'Advantage card 6',
            'team_header' => 'Team — section heading',
            'team_1' => 'Team member 1 (Title=name, Subtitle=dept, Content=bio)',
            'team_2' => 'Team member 2',
            'team_3' => 'Team member 3',
            'team_4' => 'Team member 4',
            'team_5' => 'Team member 5 (optional)',
            'team_6' => 'Team member 6 (optional)',
            'team_7' => 'Team member 7 (optional)',
            'team_8' => 'Team member 8 (optional)',
            'team_cta' => 'Team — CTA button (Title + Link)',
        ],
        'services' => ['hero' => 'Services page — hero'],
        'products' => ['hero' => 'Products page — hero'],
        'careers' => ['hero' => 'Careers page — hero'],
        'blogs' => ['hero' => 'Blogs page — hero'],
        'contact' => [
            'hero' => 'Contact page — hero',
            'contact_info' => 'Contact side — image (optional)',
            'section_heading' => 'Contact — left heading (e.g. Get in Touch)',
            'form_heading' => 'Contact — form heading (e.g. Send a Message)',
            'label_email' => 'Contact — Email label',
            'label_phone' => 'Contact — Phone label',
            'label_address' => 'Contact — Address label',
            'label_name' => 'Form — Name label',
            'label_message' => 'Form — Message label',
            'label_subject' => 'Form — Subject label',
            'submit_button' => 'Form — Submit button text',
        ],
        'faq' => ['hero' => 'FAQ page — hero'],
    ],

    'hints' => [
        'hero_bg' => 'Full-width background behind the hero section.',
        'hero_image' => 'Fallback single hero image if carousel slides are empty.',
        'hero_slide_1' => 'Upload hero carousel image (recommended 800×900px).',
        'hero_slide_2' => 'Upload hero carousel image (recommended 800×900px).',
        'hero_slide_3' => 'Upload hero carousel image (recommended 800×900px).',
        'hero_slide_4' => 'Upload hero carousel image (recommended 800×900px).',
        'stat_1' => 'Title = number (e.g. 1,000+), Subtitle = label under the number.',
        'stat_2' => 'Title = number (e.g. 24/7), Subtitle = label under the number.',
        'stat_3' => 'Title = number (e.g. 50+), Subtitle = label under the number.',
        'why_partner_1' => 'Icon field: emoji or Font Awesome class (e.g. fa-bolt). Title + Content required.',
        'process_image_1' => 'Left-side image in the Process section carousel.',
        'process_image_2' => 'Left-side image in the Process section carousel.',
        'process_image_3' => 'Left-side image in the Process section carousel.',
        'process_step_1' => 'Title = card heading, Content = description. Shown as numbered process card.',
        'process_step_2' => 'Title = card heading, Content = description.',
        'process_step_3' => 'Title = card heading, Content = description.',
        'process_step_4' => 'Title = card heading, Content = description.',
        'impact_1' => 'Title = number/stat, Subtitle = label.',
        'testimonial_1' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_2' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'testimonial_3' => 'Content = quote, Title = person name, Subtitle = role. Upload avatar image.',
        'gallery_1' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_2' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_3' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_4' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_5' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_6' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_7' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'gallery_8' => 'Upload gallery image for Operations in Motion (recommended 560×400px).',
        'site_logo_desktop' => 'Shown in the header on desktop screens.',
        'site_logo_mobile' => 'Shown in the header on mobile screens.',
        'site_logo_footer' => 'Shown in the website footer.',
        'footer_tagline' => 'Short description shown below the footer logo.',
        'social_instagram' => 'Use the Link field for the full Instagram URL.',
        'social_linkedin' => 'Use the Link field for the full LinkedIn URL.',
        'milestone_1' => 'Subtitle = year, Title = milestone name, Content = description.',
        'location_1' => 'Title = city name, Subtitle = office type (e.g. Head Office).',
        'hero_meta_1' => 'Title = label (ORIGIN), Subtitle = value (Bihar, India).',
        'story' => 'Put each paragraph on a new line. Shown under the story heading.',
        'story_image' => 'Upload photo. Title becomes the floating photo tag (e.g. Distribution Hub).',
        'about_stat_1' => 'Title = number (100+), Subtitle = label (Business Clients Served).',
        'vision_quote' => 'Content = the vision quote text.',
        'issue_1' => 'Title = issue name, Content = problem text, Subtitle = solution (shown in orange).',
        'advantage_1' => 'Title = card heading, Content = description, Icon = Font Awesome class (fa-layers).',
        'team_1' => 'Title = name, Subtitle = department tag, Content = bio. Upload photo. Icon = orange or blue for tag color.',
        'team_cta' => 'Title = button text, Link = URL (default Careers page).',
    ],
];
